import type {Metadata} from "next";
import {Inter, Raleway} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"
import {ThemeProvider} from "next-themes";
import React from "react";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner"



const raleway = Raleway({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}:
                                       Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={raleway.className+" overflow-x-clip"}>
            <ReactQueryProvider>

                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="w-screen flex border-b-[0.5px] flex-col items-center justify-center">
                    <Navbar/>
                    </div>
                    <main>
                        {children}
                    </main>
                    <Toaster />
                </ThemeProvider>
            </ReactQueryProvider>
            </body>
        </html>
    );
}
